# Generated by Django 5.0.3 on 2024-03-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akademisyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('sifre', models.CharField(max_length=100)),
            ],
        ),
    ]
