# Generated by Django 5.0.3 on 2024-03-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_qrcodedata_delete_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodedata',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='data',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
