# Generated by Django 5.0.3 on 2024-03-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_qrdata_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrdata',
            name='okul_numarasi',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
