# Generated by Django 5.0.2 on 2024-05-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_qrdata_csrf_token_qrdata_scanned'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_data', models.CharField(max_length=255)),
                ('csrf_token', models.CharField(max_length=255)),
                ('okul_numarasi', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='QRData',
        ),
    ]
