# Generated by Django 5.0.2 on 2024-05-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_qrdata2_delete_qrdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QRData2',
            new_name='QRData',
        ),
    ]
