# Generated by Django 5.0.2 on 2024-05-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_qrcodedata2_qrdata2_delete_qrcodedata_delete_qrdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QRCodeData2',
            new_name='QRCodeData',
        ),
        migrations.RenameModel(
            old_name='QRData2',
            new_name='QRData',
        ),
    ]
