# Generated by Django 5.0.2 on 2024-05-29 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_rename_qrcodedata2_qrcodedata_rename_qrdata2_qrdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='akademisyen',
        ),
        migrations.RenameModel(
            old_name='QRData',
            new_name='QRData2',
        ),
        migrations.CreateModel(
            name='Akademisyen2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('sifre', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='qrdata2',
            name='akademisyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.akademisyen2'),
        ),
        migrations.DeleteModel(
            name='Akademisyen',
        ),
        migrations.DeleteModel(
            name='QRCodeData',
        ),
    ]
