# Generated by Django 5.0.2 on 2024-05-29 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_qrcodedata2_remove_qrcodedata_akademisyen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Akademisyen2',
            new_name='Akademisyen',
        ),
        migrations.RenameModel(
            old_name='QRCodeData2',
            new_name='QRCodeData',
        ),
        migrations.RenameModel(
            old_name='QRData2',
            new_name='QRData',
        ),
    ]
