# Generated by Django 5.0.2 on 2024-05-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_akademisyen2_akademisyen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akademisyen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='akademisyen',
        ),
    ]
